### ISSUE TITLE
Site Navigation focus gets cut off when focused

### ISSUE THREAD

**Issue by Littletonconnor** [IHIutch/draft-ui#16]
There seems to be a small visual bug when site navigation links are focused:

See screenshot for example:
![CleanShot 2023-12-30 at 16 48 57](https://github.com/IHIutch/draft-ui/assets/26093912/335c43f9-8622-4d0b-92e7-42e32c88be93)

If we apply `pl-3` (we apply pr-3 to each `<LinkList />` already) then the focused state would no longer be cut off. 
![CleanShot 2023-12-30 at 16 55 01](https://github.com/IHIutch/draft-ui/assets/26093912/8e8e61eb-888c-46d4-ae06-3084e86e3121)

Any thoughts? Happy to make a fix for this if we think it makes sense 👍

**Comment by IHIutch** [comment]
Good catch. Ideally, I think we could add a negative margin and padding on the `<nav>` component (since its the container with the overflow) so that stays in the same spot it was in before but allows room links' ring and add padding on the link so that the spacing from the outline feels nice.

<img width="270" alt="image" src="https://github.com/IHIutch/draft-ui/assets/20825047/e84a21b5-d199-4fa9-a56f-ea08da2e1cd8">


This is also happening to the "On this Page" links too if you wanted to take a stab at that as well. Happy to take a look at a PR! Thanks

**Comment by Littletonconnor** [comment]
I like the padding/-margin idea a lot! Just pushed a fix which should address the `On this Page` links as well.
